import type { Metadata } from 'next';
import { Inter, Outfit } from 'next/font/google';
import './globals.css';
import QueryProvider from '@/lib/QueryProvider';

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
});

const outfit = Outfit({
    variable: '--font-outfit',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${inter.variable} ${outfit.variable} antialiased`}
            >
                <main className="max-w-[1250px] mx-auto relative h-full">
                    <QueryProvider>{children}</QueryProvider>
                </main>
            </body>
        </html>
    );
}
